apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=


# here we need to add base64 encoded data instead of plain text
# echo -n 'text-here' | base64   /in unix
# [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("text-here"))  /in windows
